CREATE TABLE PERSONAS (
	nro_doc INT NOT NULL,
	nom_ape VARCHAR(200) NOT NULL,
	PRIMARY KEY(nro_doc)
);
INSERT INTO PERSONAS (nro_doc, nom_ape) VALUES (25017972,'JUAN PEREZ');
INSERT INTO PERSONAS (nro_doc, nom_ape) VALUES (25079318,'PEPE JUAREZ');
INSERT INTO PERSONAS (nro_doc, nom_ape) VALUES (30123121,'SANCO PANSA');
INSERT INTO PERSONAS (nro_doc, nom_ape) VALUES (12312312,'PEPINO CUEVAS');